# Generated by Django 5.0.14 on 2026-07-15 15:57

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(db_index=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_type', models.CharField(choices=[('Police', 'Police'), ('Fire Department', 'Fire Department'), ('Ambulance', 'Ambulance'), ('Hospital', 'Hospital'), ('Disaster Risk Reduction Office', 'Disaster Risk Reduction Office'), ('Rescue Team', 'Rescue Team'), ('Coast Guard', 'Coast Guard'), ('Barangay Emergency Response Team', 'Barangay Emergency Response Team'), ('Social Welfare Office', 'Social Welfare Office'), ('Electric Utility', 'Electric Utility'), ('Water Utility', 'Water Utility'), ('Other', 'Other')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('primary_phone_number', models.CharField(max_length=30)),
                ('secondary_phone_number', models.CharField(blank=True, max_length=30)),
                ('hotline_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('province', models.CharField(db_index=True, max_length=100)),
                ('city_municipality', models.CharField(db_index=True, max_length=100)),
                ('barangay', models.CharField(db_index=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True)),
                ('availability', models.CharField(choices=[('24/7', '24/7'), ('Office Hours', 'Office Hours'), ('On Call', 'On Call'), ('Temporarily Unavailable', 'Temporarily Unavailable')], db_index=True, max_length=30)),
                ('office_hours', models.CharField(blank=True, max_length=120)),
                ('emergency_types', models.JSONField(default=list)),
                ('priority_order', models.PositiveIntegerField(default=0)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='contacts/', validators=[common.validators.validate_upload])),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority_order', 'organization_name'],
            },
        ),
    ]
