# Generated by Django 5.0.14 on 2026-07-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencycontact',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='longitude',
        ),
    ]
