# Generated by Django 5.0.14 on 2026-07-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('fil', 'Filipino'), ('ceb', 'Bisaya')], max_length=3, unique=True),
        ),
    ]
