# Generated by Django 5.0.14 on 2026-07-15 15:57

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Before an Emergency', 'Before an Emergency'), ('During an Emergency', 'During an Emergency'), ('After an Emergency', 'After an Emergency'), ('First Aid', 'First Aid'), ('Evacuation', 'Evacuation'), ('Disaster Preparedness', 'Disaster Preparedness'), ('Safety Procedures', 'Safety Procedures'), ('Emergency Communication', 'Emergency Communication')], db_index=True, max_length=40)),
                ('emergency_type', models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Typhoon', 'Typhoon'), ('Fire', 'Fire'), ('Landslide', 'Landslide'), ('Tsunami', 'Tsunami'), ('Volcanic Eruption', 'Volcanic Eruption'), ('Medical Emergency', 'Medical Emergency'), ('Armed Conflict', 'Armed Conflict'), ('General Emergency', 'General Emergency')], db_index=True, max_length=40)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='guidelines/images/', validators=[common.validators.validate_upload])),
                ('attachment', models.FileField(blank=True, null=True, upload_to='guidelines/attachments/', validators=[common.validators.validate_upload])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=12)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
