# Generated by Django 5.0.14 on 2026-07-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guideline',
            options={'ordering': ['title']},
        ),
    ]
