# Generated by Django 5.0.14 on 2026-07-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0002_alter_guideline_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
