# Generated by Django 5.0.14 on 2026-07-15 16:53

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0003_alter_guideline_slug'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideline',
            name='attachment',
        ),
        migrations.AddField(
            model_name='guideline',
            name='safety_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guideline',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='GuidelineMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media_file', models.FileField(upload_to='guidelines/media/', validators=[common.validators.validate_media_upload])),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='guidelines.guideline')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineMediaTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Needs Review', 'Needs Review'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_description', models.TextField(blank=True)),
                ('caption_text', models.TextField(blank=True)),
                ('subtitle_file', models.FileField(blank=True, null=True, upload_to='guidelines/subtitles/', validators=[common.validators.validate_subtitle])),
                ('alternative_media_file', models.FileField(blank=True, null=True, upload_to='guidelines/media/language/', validators=[common.validators.validate_media_upload])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guidelines.guidelinemedia')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuidelineTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Needs Review', 'Needs Review'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translated_title', models.CharField(max_length=255)),
                ('translated_summary', models.TextField()),
                ('translated_content', models.TextField()),
                ('translated_safety_instructions', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='guidelines.guideline')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='guidelinemediatranslation',
            constraint=models.UniqueConstraint(fields=('media', 'language'), name='unique_media_language'),
        ),
        migrations.AddConstraint(
            model_name='guidelinetranslation',
            constraint=models.UniqueConstraint(fields=('guideline', 'language'), name='unique_guideline_language'),
        ),
    ]
