# Generated by Django 5.2.16 on 2026-08-01 14:38

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0004_remove_guideline_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidelinemedia',
            name='external_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='guidelinemedia',
            name='source_type',
            field=models.CharField(choices=[('upload', 'Uploaded file'), ('link', 'Embedded link')], default='upload', max_length=10),
        ),
        migrations.AlterField(
            model_name='guidelinemedia',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='guidelines/media/', validators=[common.validators.validate_media_upload]),
        ),
        migrations.AlterField(
            model_name='guidelinemedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('svg', 'SVG'), ('icon', 'Icon')], max_length=5),
        ),
    ]
