# Generated by Django 5.2.16 on 2026-08-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0005_guidelinemedia_external_url_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guidelinemedia',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'upload'), models.Q(('media_file', ''), _negated=True), ('external_url', '')), models.Q(('source_type', 'link'), ('media_file', ''), models.Q(('external_url', ''), _negated=True)), _connector='OR'), name='guideline_media_has_one_source'),
        ),
    ]
