providers = ["python"]

[variables]
PKG_CONFIG_PATH = "/root/.nix-profile/lib/pkgconfig"
COOLIFY_FQDN = "pccsg4g4k8ws8cggw4o4oso4.76.13.217.76.sslip.io"
COOLIFY_URL = "http://pccsg4g4k8ws8cggw4o4oso4.76.13.217.76.sslip.io"
SECURE_SSL_REDIRECT = "false"

[phases.setup]
nixPkgs = [
    "...",
    "pkg-config",
]
nixLibs = [
    "...",
    "libmysqlclient",
]

[phases.build]
cmds = [
    "SECRET_KEY=nixpacks-build-only USE_SQLITE=true python manage.py collectstatic --noinput",
]

[start]
cmd = "python -m deploy.entrypoint"
