# Generated by Django 5.0.14 on 2026-07-15 15:57

import common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('center_code', models.CharField(max_length=40, unique=True)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('province', models.CharField(db_index=True, max_length=100)),
                ('city_municipality', models.CharField(db_index=True, max_length=100)),
                ('barangay', models.CharField(db_index=True, max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=7, max_digits=10)),
                ('total_capacity', models.PositiveIntegerField()),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('available_slots', models.PositiveIntegerField(default=0, editable=False)),
                ('contact_person', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=30)),
                ('alternative_contact_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('operating_status', models.CharField(choices=[('Operational', 'Operational'), ('Temporarily Closed', 'Temporarily Closed'), ('Under Maintenance', 'Under Maintenance'), ('Full', 'Full'), ('Inactive', 'Inactive')], db_index=True, default='Operational', max_length=30)),
                ('availability_status', models.CharField(choices=[('Available', 'Available'), ('Limited', 'Limited'), ('Full', 'Full'), ('Closed', 'Closed')], db_index=True, default='Available', max_length=20)),
                ('facility_type', models.CharField(choices=[('School', 'School'), ('Gymnasium', 'Gymnasium'), ('Barangay Hall', 'Barangay Hall'), ('Covered Court', 'Covered Court'), ('Community Center', 'Community Center'), ('Government Building', 'Government Building'), ('Religious Facility', 'Religious Facility'), ('Temporary Shelter', 'Temporary Shelter'), ('Other', 'Other')], db_index=True, max_length=40)),
                ('supported_emergency_types', models.JSONField(default=list)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_water_supply', models.BooleanField(default=False)),
                ('has_restroom', models.BooleanField(default=False)),
                ('has_medical_area', models.BooleanField(default=False)),
                ('has_kitchen', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('is_pwd_accessible', models.BooleanField(default=False)),
                ('accepts_pets', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evacuation_centers/', validators=[common.validators.validate_upload])),
                ('remarks', models.TextField(blank=True)),
                ('last_capacity_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='evacuationcenter',
            constraint=models.CheckConstraint(check=models.Q(('total_capacity__gte', 0)), name='evac_capacity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='evacuationcenter',
            constraint=models.CheckConstraint(check=models.Q(('current_occupancy__gte', 0)), name='evac_occupancy_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='evacuationcenter',
            constraint=models.CheckConstraint(check=models.Q(('current_occupancy__lte', models.F('total_capacity'))), name='evac_occupancy_lte_capacity'),
        ),
    ]
