# Generated by Django 5.0.14 on 2026-07-15 16:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evacuation_centers', '0001_initial'),
        ('languages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvacuationCenterTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Needs Review', 'Needs Review'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translated_description', models.TextField()),
                ('translated_facility_description', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='evacuation_centers.evacuationcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='languages.language')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='evacuationcentertranslation',
            constraint=models.UniqueConstraint(fields=('center', 'language'), name='unique_center_language'),
        ),
    ]
