from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include,path
from django.views.generic import RedirectView
from django.views.static import serve as serve_static
from drf_spectacular.views import SpectacularAPIView,SpectacularRedocView,SpectacularSwaggerView
from rest_framework.routers import DefaultRouter
from accounts.views import *
from alerts.views import CitizenAlertViewSet,ResponderAlertViewSet,AlertTranslationViewSet,CitizenCalamityViewSet,ResponderCalamityViewSet,CalamityTranslationViewSet
from audit_logs.views import AuditViewSet
from emergency_contacts.views import CitizenContactViewSet,ResponderContactViewSet,ContactTranslationViewSet
from evacuation_centers.views import CitizenEvacuationViewSet,ResponderEvacuationViewSet,EvacuationTranslationViewSet
from go_bag.views import CitizenGoBagViewSet,ResponderGoBagViewSet,GoBagTranslationViewSet
from guidelines.views import CitizenGuidelineViewSet,ResponderGuidelineViewSet,GuidelineTranslationViewSet,GuidelineMediaViewSet,GuidelineMediaTranslationViewSet
from languages.views import PublicLanguageViewSet,ResponderLanguageViewSet

citizen=DefaultRouter(); citizen.register("languages",PublicLanguageViewSet,basename="citizen-languages"); citizen.register("go-bag",CitizenGoBagViewSet,basename="citizen-go-bag"); citizen.register("calamities",CitizenCalamityViewSet,basename="citizen-calamities"); citizen.register("guidelines",CitizenGuidelineViewSet,basename="citizen-guidelines"); citizen.register("evacuation-centers",CitizenEvacuationViewSet,basename="citizen-evacuation"); citizen.register("emergency-contacts",CitizenContactViewSet,basename="citizen-contacts"); citizen.register("alerts",CitizenAlertViewSet,basename="citizen-alerts")
responder=DefaultRouter(); responder.register("accounts",UserViewSet,basename="responder-accounts"); responder.register("languages",ResponderLanguageViewSet,basename="responder-languages"); responder.register("go-bag",ResponderGoBagViewSet,basename="responder-go-bag"); responder.register("go-bag-translations",GoBagTranslationViewSet,basename="go-bag-translations"); responder.register("calamities",ResponderCalamityViewSet,basename="responder-calamities"); responder.register("calamity-translations",CalamityTranslationViewSet,basename="calamity-translations"); responder.register("guidelines",ResponderGuidelineViewSet,basename="responder-guidelines"); responder.register("guideline-translations",GuidelineTranslationViewSet,basename="guideline-translations"); responder.register("guideline-media",GuidelineMediaViewSet,basename="guideline-media"); responder.register("guideline-media-translations",GuidelineMediaTranslationViewSet,basename="guideline-media-translations"); responder.register("evacuation-centers",ResponderEvacuationViewSet,basename="responder-evacuation"); responder.register("evacuation-center-translations",EvacuationTranslationViewSet,basename="evacuation-translations"); responder.register("emergency-contacts",ResponderContactViewSet,basename="responder-contacts"); responder.register("emergency-contact-translations",ContactTranslationViewSet,basename="contact-translations"); responder.register("alerts",ResponderAlertViewSet,basename="responder-alerts"); responder.register("alert-translations",AlertTranslationViewSet,basename="alert-translations"); responder.register("audit-logs",AuditViewSet,basename="audit-logs")
urlpatterns=[path("",RedirectView.as_view(pattern_name="swagger-ui",permanent=False)),path("admin/",admin.site.urls),path("static/<path:path>",serve_static,{"document_root":settings.STATIC_ROOT}),path("api/schema/",SpectacularAPIView.as_view(),name="schema"),path("api/docs/",SpectacularSwaggerView.as_view(url_name="schema"),name="swagger-ui"),path("api/redoc/",SpectacularRedocView.as_view(url_name="schema"),name="redoc"),path("api/citizen/",include(citizen.urls)),path("api/responder/auth/login/",LoginView.as_view()),path("api/responder/auth/refresh/",VerifiedTokenRefreshView.as_view()),path("api/responder/auth/logout/",LogoutView.as_view()),path("api/responder/auth/forgot-password/",ForgotPasswordView.as_view()),path("api/responder/auth/reset-password/",ResetPasswordView.as_view()),path("api/responder/auth/change-password/",ChangePasswordView.as_view()),path("api/responder/auth/profile/",ProfileView.as_view()),path("api/responder/",include(responder.urls))]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
