# Generated by Django 5.0.14 on 2026-07-15 15:57

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evacuation_centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_code', models.CharField(editable=False, max_length=40, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('message', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('alert_type', models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Typhoon', 'Typhoon'), ('Fire', 'Fire'), ('Landslide', 'Landslide'), ('Tsunami', 'Tsunami'), ('Volcanic Eruption', 'Volcanic Eruption'), ('Medical Emergency', 'Medical Emergency'), ('Road Closure', 'Road Closure'), ('Missing Person', 'Missing Person'), ('Evacuation Notice', 'Evacuation Notice'), ('Weather Advisory', 'Weather Advisory'), ('Public Safety', 'Public Safety'), ('General Emergency', 'General Emergency')], db_index=True, max_length=40)),
                ('severity_level', models.CharField(choices=[('Information', 'Information'), ('Advisory', 'Advisory'), ('Warning', 'Warning'), ('Severe', 'Severe'), ('Critical', 'Critical')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Active', 'Active'), ('Expired', 'Expired'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=15)),
                ('source', models.CharField(max_length=180)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('province', models.CharField(blank=True, db_index=True, max_length=100)),
                ('city_municipality', models.CharField(blank=True, db_index=True, max_length=100)),
                ('barangay', models.CharField(blank=True, db_index=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True)),
                ('radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('affected_areas', models.JSONField(default=list)),
                ('evacuation_required', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='alerts/attachments/', validators=[common.validators.validate_upload])),
                ('image', models.ImageField(blank=True, null=True, upload_to='alerts/images/', validators=[common.validators.validate_upload])),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_alerts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('recommended_evacuation_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evacuation_centers.evacuationcenter')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='emergencyalert',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('starts_at'))), name='alert_expiry_after_start'),
        ),
    ]
