# Generated by Django 5.0.14 on 2026-07-15 15:57

import common.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoBagItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Food and Water', 'Food and Water'), ('Medical Supplies', 'Medical Supplies'), ('Communication', 'Communication'), ('Clothing', 'Clothing'), ('Important Documents', 'Important Documents'), ('Tools and Equipment', 'Tools and Equipment'), ('Hygiene', 'Hygiene'), ('Emergency Supplies', 'Emergency Supplies'), ('Baby Supplies', 'Baby Supplies'), ('Senior Citizen Supplies', 'Senior Citizen Supplies'), ('Pet Supplies', 'Pet Supplies'), ('Other', 'Other')], db_index=True, max_length=40)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(max_length=40)),
                ('priority_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], db_index=True, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='go_bag/', validators=[common.validators.validate_upload])),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
